name: Build and Deploy React App to Pages

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to GitHub runner

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: npm run and build
        run: |
          cd docs
          npm i
          npm run build --if-present
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3