name: Build and Deploy React App to Pages

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build_deploy_react:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to GitHub runner

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: npm run and build
        run: |
          cd docs
          npm i
          npm run build --if-present

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build